### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ridingthebulls** [villimad/Telegram-Bot-Button-Apps-Script#2]
Unable To Do So (Changing .gs To .js) :(
how did you do it? via CLASP or ...???
(Might be asking stupidly but I'm new to this coding platform and all that. please help)

**Comment by villimad** [comment]
I copied the script text and saved with arbitrary resolution.

**Comment by ridingthebulls** [comment]
sorry, but didn't get you.

**Comment by ridingthebulls** [comment]
can you please tell a little bit in detail?

**Comment by villimad** [comment]
I did not locate the script locally. I created a project at https://script.google.com/. Then I created the file bot.gs on my computer and copied the script code there (Ctrl + C) and uploaded it to Github.

**Comment by villimad** [comment]
Or are you interested in how I changed the file extension in the Git system?

**Comment by ridingthebulls** [comment]
inline keyboard is not working in my version (copied yours). thought might be due to extension... pls help

**Comment by villimad** [comment]
How are you deployed your application?

**Comment by ridingthebulls** [comment]
on google sheets script editor (Publish- Deploy as webapp).

**Comment by villimad** [comment]
Perhaps the Google script API has changed.

**Comment by villimad** [comment]
Inline keyboard, may not work due to the encoding of the " text" field.
