### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by h4xw4r** [villimad/Telegram-Bot-Button-Apps-Script#3]
I tried your script it doesn't work and the characters are all question marks

**Comment by villimad** [comment]
Question marks are inscriptions in Russian. 
How you positioned your code, this example is mainly suitable for Google App Script?
 I also advise you to look at the official information about the Telegram Api, they are quite comprehensive  [Telegram API](https://core.telegram.org/bots/api#inlinekeyboardbutton).

**Comment by h4xw4r** [comment]
Are you certain that it's working ?
